name: Build the ansible-ee image
on:
  push:
    paths-ignore:
      - .github/**
      - .gitignore
      - README.md
      - Makefile

jobs:
  build:
    runs-on:
      - STANDARD-RUNNER
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PASS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: "${{ github.ref_name == 'main' }}"
          tags: junoinnovations/ansible-ee:${{ (github.ref_name == 'main' && 'stable') }}
